default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'hoichuphong513'

development:
  <<: *default
  database: shop_admin_development

test:
  <<: *default
  database: shop_admin_test
